export const ALL_DATA_BY_CITY_NAME_REQUEST = "ALL_DATA_BY_CITY_NAME_REQUEST";
export const ALL_DATA_BY_CITY_NAME_SUCCESS = "ALL_DATA_BY_CITY_NAME_SUCCESS";
export const ALL_DATA_BY_CITY_NAME_FAILURE = "ALL_DATA_BY_CITY_NAME_FAILURE";
